image: Visual Studio 2019
configuration: Default

before_build:
    - ps: Start-FileDownload "https://developer.download.nvidia.com/compute/cuda/11.4.0/network_installers/cuda_11.4.0_win10_network.exe" -FileName "CUDA.exe"
    - ps: Start-Process -Wait "CUDA.exe" "-s nvcc_11.4 cudart_11.4" 
    - cmd: SET CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4

build:
    project: .\Source\HedgeGI.sln
    
after_build:
    - 7z a HedgeGI.zip .\Source\HedgeGI\bin\Release\HedgeGI.exe
    
artifacts:
    - path: HedgeGI.zip
      name: HedgeGI